package:
  name: arangodb
  version: "3.11.13.2"
  epoch: 0
  description: "Native multi-model database with flexible data models for documents, graphs, and key-values."
  copyright:
    - license: "BSL-1.1"

environment:
  contents:
    packages:
      - cmake
      - build-base
      - bash
      - busybox
      - systemd-dev
      - python3-dev
      - openssl-dev
      - perl
      - snappy-dev
      - lz4-dev
      - zlib-dev
      - gc-dev
      - boost-dev
      - python3-dev
      - ccache
      - vim
      - clang-16
      - clang-16-dev
      - lld
      - llvm16
      - llvm-libcxx-16
      - llvm-libcxx-16-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/arangodb/arangodb
      tag: v${{package.version}}
      expected-commit: 20631a31e4bace3df87589a1ac1d4ba5ef792363

  - name: get submodules
    runs: |
      git submodule update --init --recursive

  - name: fix CMakeFile.txt
    runs: |
      sed -i 's/NOT PORTABLE OR FORCE_SSE42/FALSE/' 3rdParty/rocksdb/CMakeLists.txt

  - runs: |
      cmake \
      -DCMAKE_C_COMPILER=clang-16 \
      -DCMAKE_CXX_COMPILER=clang++ \
      -DCMAKE_C_COMPILER_AR="/usr/bin/llvm-ar" \
      -DCMAKE_CXX_COMPILER_AR="/usr/bin/llvm-ar" \
      -DCMAKE_C_COMPILER_RANLIB="/usr/bin/llvm-ranlib" \
      -DCMAKE_CXX_COMPILER_RANLIB="/usr/bin/llvm-ranlib" \
      -DCMAKE_EXE_LINKER_FLAGS="-Wl,--build-id=sha1 -fno-stack-protector -fuse-ld=lld" \
      -DCMAKE_SHARED_LINKER_FLAGS="-fuse-ld=lld" \
      -DUSE_LIBUNWIND=true -DUSE_PRECOMPILED_V8=false \
      -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
      -DCMAKE_C_FLAGS="-fPIC" \
      -DCMAKE_CXX_FLAGS="-fPIC" \
      -DSNAPPY_INCLUDE_DIR=/usr/include \
      -DJEMALLOC_INCLUDE=/usr/include \
      -DZLIB_INCLUDE_DIR=/usr/include \
      -DUNWIND_INCLUDE_DIR=/usr/include \
      --preset community

      cmake --build --preset community --target arangodb -- -j$(nproc) VERBOSE=1

update:
  enabled: true
  github:
    identifier: arangodb/arangodb
    strip-prefix: v
    use-tag: true

  # cmake -DCMAKE_C_COMPILER=clang-16 \
  # -DCMAKE_CXX_COMPILER=clang++ \
  # -DCMAKE_C_COMPILER_AR="/usr/bin/llvm-ar" \
  # -DCMAKE_CXX_COMPILER_AR="/usr/bin/llvm-ar" \
  # -DCMAKE_C_COMPILER_RANLIB="/usr/bin/llvm-ranlib" \
  # -DCMAKE_CXX_COMPILER_RANLIB="/usr/bin/llvm-ranlib" \
  # -DCMAKE_C_FLAGS="--stdlib=libc++ -msse4.2" \
  # -DCMAKE_CXX_FLAGS="--stdlib=libc++ -msse4.2" \
  # -DCMAKE_EXE_LINKER_FLAGS="-Wl,--build-id=sha1 -fno-stack-protector -fuse-ld=lld --stdlib=libc++" \
  # -DCMAKE_SHARED_LINKER_FLAGS="-fuse-ld=lld --stdlib=libc++" \
  # -DUSE_LIBUNWIND=false \
  # --preset community

  # apk add cmake build-base bash systemd-dev python3-dev openssl-dev perl snappy-dev lz4-dev zlib-dev gc-dev boost-dev python3-dev ccache vim git clang-16 clang-16-dev lld llvm16 llvm-libcxx-16 llvm-libcxx-16-dev 
  # cd ..
  # git clone https://github.com/arangodb/arangodb.git -b v3.11.13.2
  # cd arangodb
  # git submodule update --init --recursive
  # fix rocksdb cmakefile
  # sed -i 's/NOT PORTABLE OR FORCE_SSE42/FALSE/' 3rdParty/rocksdb/CMakeLists.txt 
  # export CXX=clang++
  # export CC=clang
  # export CXXFLAGS="-fPIC -isystem /usr/include/c++/14 -isystem /usr/include/c++/14/x86_64-pc-linux-gnu"
  # export CFLAGS="-fPIC"
  # cmake -DCMAKE_C_COMPILER=clang-16 \
  # -DCMAKE_CXX_COMPILER=clang++ \
  # -DCMAKE_C_COMPILER_AR="/usr/bin/llvm-ar" \
  # -DCMAKE_CXX_COMPILER_AR="/usr/bin/llvm-ar" \
  # -DCMAKE_C_COMPILER_RANLIB="/usr/bin/llvm-ranlib" \
  # -DCMAKE_CXX_COMPILER_RANLIB="/usr/bin/llvm-ranlib" \
  # -DCMAKE_EXE_LINKER_FLAGS="-Wl,--build-id=sha1 -fno-stack-protector -fuse-ld=lld" -DCMAKE_SHARED_LINKER_FLAGS="-fuse-ld=lld" -DUSE_LIBUNWIND=true -DUSE_PRECOMPILED_V8=false -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_C_FLAGS="-fPIC" -DCMAKE_CXX_FLAGS="-fPIC" -DSNAPPY_INCLUDE_DIR=/usr/include -DJEMALLOC_INCLUDE=/usr/include -DZLIB_INCLUDE_DIR=/usr/include -DUNWIND_INCLUDE_DIR=/usr/include \
  #  --preset community
  # cmake --build --preset community --target arangodb -- -j$(nproc) VERBOSE=1

  # cmake -DCMAKE_C_COMPILER=clang-16 \
  # -DCMAKE_CXX_COMPILER=clang++ \
  # -DCMAKE_C_COMPILER_AR="/usr/bin/llvm-ar" \
  # -DCMAKE_CXX_COMPILER_AR="/usr/bin/llvm-ar" \
  # -DCMAKE_C_COMPILER_RANLIB="/usr/bin/llvm-ranlib" \
  # -DCMAKE_CXX_COMPILER_RANLIB="/usr/bin/llvm-ranlib" \
  # -DCMAKE_EXE_LINKER_FLAGS="-Wl,--build-id=sha1 -fno-stack-protector -fuse-ld=lld" \
  # -DCMAKE_SHARED_LINKER_FLAGS="-fuse-ld=lld" \
  # -DUSE_LIBUNWIND=true \
  # -DUSE_PRECOMPILED_V8=false \
  # -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
  # -DSNAPPY_INCLUDE_DIR=/usr/include \
  # -DJEMALLOC_INCLUDE=/usr/include \
  # -DZLIB_INCLUDE_DIR=/usr/include \
  # -DUNWIND_INCLUDE_DIR=/usr/include \
  # --preset community
