package:
  name: cinder-csi-plugin
  version: 1.32.0
  epoch: 0
  description: Cinder-CSI-Plugin is a Kubernetes CSI driver for provisioning and managing OpenStack Cinder volumes
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes/cloud-provider-openstack
      tag: v${{package.version}}
      expected-commit: a70c0b34244a9cf17dadd6e7a4ab9b27cd486700

  - uses: go/build
    with:
      packages: ./cmd/cinder-csi-plugin
      modroot: .
      output: cinder-csi-plugin
      ldflags: -X k8s.io/component-base/version.gitVersion=v${{package.version}} -X k8s.io/cloud-provider-openstack/pkg/version.Version=v${{package.version}}

  - uses: strip

update:
  enabled: true
  github:
    strip-prefix: v
    identifier: kubernetes/cloud-provider-openstack

test:
  environment:
    contents:
      packages:
        - curl
  pipeline:
    - runs: |
        # cinder-csi-plugin depends on a running openstack environment, which does not support alpine based operating systems
        curl -o cloud-config https://raw.githubusercontent.com/kubernetes/cloud-provider-openstack/251508d52818825b2cf2d62ff0a205d5eb352990/manifests/controller-manager/cloud-config
        sed -i 's/^tenant-id=.*/tenant-id=test-tenant-id/' cloud-config
        sed -i 's/^domain-id=.*/domain-id=test-domain-id/' cloud-config
        cinder-csi-plugin --cloud-config cloud-config --endpoint=unix:///csi/csi.sock 2>&1 | grep "Failed to GetOpenStackProvider"
        
