package:
  name: font-adobe-utopia-type1
  version: 1.0.5
  epoch: 0
  description: "Adobe Utopia Type1 fonts"
  copyright:
    - license: Freely Redistributable

environment:
  contents:
    packages:
      - autoconf
      - automake
      - bdftopcf
      - build-base
      - busybox
      - ca-certificates-bundle
      - font-util
      - font-util-dev
      - mkfontscale
      - util-macros

pipeline:
  - uses: fetch
    with:
      uri: https://xorg.freedesktop.org/archive/individual/font/font-adobe-utopia-type1-${{package.version}}.tar.xz
      expected-sha512: e30f4c7702f47a3a42206975fbcfec058317681956d246411e50e372b669bdc875c5d7fe28bad7d298bc61b71a997c7836fb6ac16effd223a96723a6e9ece649

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 17201

test:
  pipeline:
    - uses: test/fonts
