package:
  name: font-dec-misc
  version: 1.0.4
  epoch: 0
  description: "DEC misc fonts"
  copyright:
    - license: Freely Redistributable

environment:
  contents:
    packages:
      - autoconf
      - automake
      - bdftopcf
      - build-base
      - busybox
      - ca-certificates-bundle
      - font-util
      - font-util-dev
      - mkfontscale
      - util-macros

pipeline:
  - uses: fetch
    with:
      uri: https://xorg.freedesktop.org/archive/individual/font/font-dec-misc-${{package.version}}.tar.xz
      expected-sha512: bf6c0e4924835346f1f7913a04fa3903a7c55d292317526dd8eaa799dfb3b52eb2157c34692d659b41a18123af8389785dcb4aa0c31fc387cb368642801c3335

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 17211

test:
  pipeline:
    - uses: test/fonts
