package:
  name: font-cursor-misc
  version: 1.0.4
  epoch: 0
  description: "Cursor misc fonts"
  copyright:
    - license: Freely Redistributable

environment:
  contents:
    packages:
      - autoconf
      - automake
      - bdftopcf
      - build-base
      - busybox
      - ca-certificates-bundle
      - font-util
      - font-util-dev
      - mkfontscale
      - util-macros

pipeline:
  - uses: fetch
    with:
      uri: https://xorg.freedesktop.org/archive/individual/font/font-cursor-misc-${{package.version}}.tar.xz
      expected-sha512: 22bd86a81cdfb1e17f885dc3961071c08920171a6f0736ae52d95c8e576b1debc7570aa3b7e1007f474b50435fba411f0eb1847894e8b52f6e6268d91cf9f2db

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 17210

test:
  pipeline:
    - uses: test/fonts
