package:
  name: vela-core
  version: 1.9.13
  epoch: 0
  description: The Modern Application Platform.
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      expected-commit: d56da069eb5ee06d9716810e828d6370b93b70ba
      repository: https://github.com/kubevela/kubevela
      tag: v${{package.version}}

  - uses: go/build
    with:
      output: vela-core
      ldflags: -s -w -X 'github.com/oam-dev/kubevela/version.VelaVersion=v${{package.version}}' -X 'github.com/oam-dev/kubevela/version.GitRevision=$(git rev-parse HEAD)'
      packages: ./cmd/core/

  - uses: strip

update:
  enabled: true
  github:
    identifier: kubevela/kubevela
    strip-prefix: v
    tag-filter: v
    use-tag: true

test:
  pipeline:
    - runs: |
        vela-core --help
